baseURL = "https://juliemitchell.co/"
languageCode = "en-gb"
title = "Julie Mitchell"
[outputs]
home = ["HTML", "RSS", "JSON"]
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
