version: '3.2'
services:
  web:
    image: maxisme/juliemitchell.co:latest
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.juliemitchellco.rule=Host(`juliemitchell.co`)"
        - "traefik.http.services.juliemitchellco.loadbalancer.server.port=8080"
        - "traefik.http.routers.juliemitchellco.middlewares=404"
    networks:
      - traefik

networks:
  traefik:
    external: true