backend:
  name: github
  repo: maxisme/juliemitchell.co
media_folder: static/images
public_folder: /images
collections:
  - name: 'work'
    label: 'Work'
    folder: 'content/work'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text', default: 'Oil on canvas' }
      - { label: 'Price', name: 'price', widget: 'number', required: false }
      - { label: "Type", name: "type", widget: "select", options: [ "Still Life", "Landscape"]}
  - name: 'about'
    label: 'About'
    files:
      - label: "About Page"
        name: "about"
        file: "/content/_index.md"
        fields:
          - { label: About, name: about, widget: markdown }